### ISSUE TITLE
Filter by Tag

### ISSUE THREAD

**Issue by cloverww04** [cloverww04/rare#21]
Filter by Tag:
- create an endpoint that selects all Posts where the PostTags tag_id matches the Tags id

# User Story
user should see all the posts that match the tag that was chosen from a drop down menu on the front end.

# Acceptance Criteria
When the correct posts are being filtered by the tag

# Dependecies
- This depends on the Posts id matching the PostTags post_id
- This depends on the PostTags tag_id matching the Tags id.

# Dev Notes
- The Post class should be created and it's properties functioning as intended.
- PostTags should be populated with a post_id and tag_id before being able to filter by tags.

**Comment by dimitricbrown** [comment]
Done!
