### ISSUE TITLE
Create Tag Endpoint

### ISSUE THREAD

**Issue by Oktiv20** [cloverww04/rare#26]
# User Story
When the user navigates to the tag list page, there should be an option to "create a new tag". After the user fills out the form and submits, the tag should be added and the list should update with that new tag.

# Acceptance Criteria
A create tag endpoint should be used to post the content from the submitted form to the database after completion.

# Dependecies
Posts must be created and be able to be called on so that a user can post a tag and edit that tag.

# Dev Notes
In tagData, write a function that takes the postId and creates a new tag based off that id so that it is associated with the correct Post.

**Comment by dimitricbrown** [comment]
Done!
