### ISSUE TITLE
Filter by category

### ISSUE THREAD

**Issue by cloverww04** [cloverww04/rare#29]
Filter by category: 

- create and end point that searches through the Posts class for a cateogry_id matching the id in the Categories class.

# User Story
The user should see all posts matching the category_id in the posts class.

# Acceptance Criteria
When the user see all posts matching the category that was selected.

# Dependecies
This depends on the Cateogires and Posts class being setup and functioning properly.

# Dev Notes
The Categories class and Posts class should be set up before this issue can be worked on.

**Comment by dimitricbrown** [comment]
Completed!
