### ISSUE TITLE
Delete a Comment

### ISSUE THREAD

**Issue by scdorr86** [cloverww04/rare#3]
# User Story
Given a user is on the comments page for a post
When they are the author of a comment
Then they should see a trash can icon
And when they click the trash can
Then that comment should be deleted

# Acceptance Criteria
On call the endpoint should delete the user comment selected

# Dependecies
endpoints created to create comment, get comment, and delete comment

# Dev Notes
endpoints created to create comment, get comment, and delete comment

**Comment by dimitricbrown** [comment]
User can successfully delete a comment
