### ISSUE TITLE
Create Comment Endpoint

### ISSUE THREAD

**Issue by Oktiv20** [cloverww04/rare#31]
# User Story
When a user chooses to comment on a post, they should see a text area to enter their comment and after they submit the comment, they should be able to see that comment along with all of the other comments on the post.

# Acceptance Criteria
A comment endpoint should be used to post the comment information from the text area to the database.

# Dependecies
Users must be able to post a comment based off their "id" and the "comment id" should be linked to the "posts id"

**Comment by dimitricbrown** [comment]
User can successfully create a new comment to a single post.
