### ISSUE TITLE
Create Category Endpoint

### ISSUE THREAD

**Issue by Oktiv20** [cloverww04/rare#7]
# User Story
Create A Category:
- When the user fills out the form and submits
- The category should be added and the list should update

# Acceptance Criteria
Endpoints should be created so that when a user calls the create category endpoint the category the user created is posted to the database.

# Dependecies
Categories should be created in accordance with the proposed ERD

# Dev Notes
Must be created so that users can assign posts to the categories

**Comment by dimitricbrown** [comment]
User can successfully create a new category to add the current categories list.
